//Type
export const ADD_TODO = 'ADD_TODO';
export const COMPLETE_TODO = 'COMPLETE_TODO';
export const RECEIVE_NEW_INFO = 'RECEIVE_NEW_INFO';
export const RECEIVE_CUSTUMER_DATA = 'RECEIVE_CUSTUMER_DATA';
export const RECEIVE_INVOICES_LIST = 'RECEIVE_INVOICES_LIST';
export const RECEIVE_INVOICES_ITEMS = 'RECEIVE_INVOICES_ITEMS';