export const STATIONS_TYPES_GET = 'STATIONS_TYPES_GET';

//Users const
export const ADMINS_GET = 'ADMINS_GET';
export const CLIENTS_GET = 'CLIENTS_GET';
export const MANAGER_GET = 'MANAGER_GET';

export const SERVICES_GET = 'SERVICES_GET';

export const ORDERS_BY_DEALER = 'ORDERS_BY_DEALER';
export const ORDERS_NEW_GET = 'ORDERS_NEW_GET';
export const ORDERS_CANCELED_GET = 'ORDERS_CANCELED_GET';
export const ORDERS_IN_PROGRESS_GET = 'ORDERS_IN_PROGRESS_GET';
export const ORDERS_FINISHED_GET = 'ORDERS_FINISHED_GET';

export const DELIVERY_TYPES_GET = 'DELIVERY_TYPES_GET';
export const PAYMENT_TYPES_GET = 'PAYMENT_TYPES_GET';
export const CLIENT_ORDER_STATUS_GET = 'CLIENT_ORDER_STATUS_GET';
export const SERVICE_CENTER_CONTACT_GET = 'SERVICE_CENTER_CONTACT_GET';
export const DILLERS_GET = 'DILLERS_GET';
export const STATIONS_GET = 'STATIONS_GET';
export const STATIONS_BY_DILLER_GET = 'STATIONS_BY_DILLER_GET';
export const ARTICLE_GET = 'ARTICLE_GET';
export const SERVICE_TIRE_REPAIR_TYPE_GET = 'SERVICE_TIRE_REPAIR_TYPE_GET';
export const DISK_REPAIR_TYPE_GET = 'DISK_REPAIR_TYPE_GET';


const MAP_API_KEY = 'AIzaSyCnDXfbo29jCtJApBOFAkCRLGTEhhzFEcU';

export const FEEDBACK_TIRE_CENTER_BY_STATION_GET = 'FEEDBACK_TIRE_CENTER_BY_STATION_GET';
export const FEEDBACK_TIRE_CENTER_ON_MODERATION_GET = 'FEEDBACK_TIRE_CENTER_ON_MODERATION_GET';
export const FEEDBACK_TIRE_CENTER_PUBLISHED_GET = 'FEEDBACK_TIRE_CENTER_PUBLISHED_GET';
export const FEEDBACK_TIRE_CENTER_REMOVED_GET = 'FEEDBACK_TIRE_CENTER_REMOVED_GET';

export const COMPLEX_SERVICE_AUTO_TYPE_GET = 'COMPLEX_SERVICE_AUTO_TYPE_GET';
export const COMPLEX_SERVICE_DISC_SIZE_GET = 'COMPLEX_SERVICE_DISC_SIZE_GET';
export const COMPLEX_SERVICE_TIREFITTING_TYPE_GET = 'COMPLEX_SERVICE_TIREFITTING_TYPE_GET';
export const COMPLEX_SERVICE_GET = 'COMPLEX_SERVICE_GET';