//Type
export const RESEIVE_MOVIES = 'RESEIVE_MOVIES';
export const CHANGE_VIEW_STATUS = 'CHANGE_VIEW_STATUS';
export const RESEIVE_MOVIE_DETAILS = 'RESEIVE_MOVIE_DETAILS';
export const ClEAN_MOVIE_DETAILS = 'ClEAN_MOVIE_DETAILS';
export const RESEIVE_MOVIE_RECOMENDATION = 'RESEIVE_MOVIE_RECOMENDATION';
export const ClEAN_MOVIE_RECOMENDATION = 'ClEAN_MOVIE_RECOMENDATION';
export const RESEIVE_MOVIE_COLLECTION = 'RESEIVE_MOVIE_COLLECTION';
export const ClEAN_MOVIE_COLLECTION = 'ClEAN_MOVIE_COLLECTION';
export const RESEIVE_PROGRESS_BAR = 'RESEIVE_PROGRESS_BAR';
export const ClEAN_PROGRESS_BARS = 'ClEAN_PROGRESS_BARS';
export const PASS_KEY = 'PASS_KEY';
